### PR TITLE
[Editorial] Convert some semi-colons to commas

### PR DESCRIPTION
**Pull request by tuskpot**
This completes issue #5.

I left the semi-colons in some long sentences with more complex phrasing, where they seemed more purposeful. The complete list is below. I'm less confident about some of these, so I left them alone. If you'd prefer to see any of these changed also, let me know and I'm happy to update the pull request.

> He capped the climax, however, by accidentally dropping a large handful, warm, on top of Celeste’s head, aggravating the offense by telling her to “go quick and soak her head;” which, although it was what she eventually did, was too much like a certain slang phrase much in vogue, for human nature to endure; and giving him an angry look, the only one on record ever given by her to a man, she rushed from the room, and was seen no more that evening.

> Then becoming aware of Miss Kling’s presence, he added to her, “I beg pardon for my abrupt entrance, but the outer door being open, I made bold to enter;” then explanatory to Cyn, “Your door was locked, as also was mine, of which Quimby has the key; and as Celeste has not yet been able to part with him, there I have been standing in the hall, like patience with a load of dandelions!”

> “Oh! it’s only fun, you know;” at which Quimby brightened, and Miss Archer inquired gayly,
> “\<i xml:lang="fr"\>Pour passer le temps?\</i\>”

> “She went away to sing out of town, let me see⁠—I forget where, and she will not return until tomorrow;” then, uneasily, “I⁠—I beg pardon, but you⁠—you mentioned the Invisible. Do you⁠—I beg pardon⁠—but do you converse as much as ever with him?”

> “Oh!” said Cyn, a light breaking in upon her. “I see, but I did not then understand you, I suppose;” rallying from her embarrassment, “my mind was so occupied with our feast, I was incapable of thinking of anything else; so please consider this an apology for the condition in which you find us, to yourself and your friend, whom, you will pardon me for reminding you, you have \<em\>not\</em\> introduced,” and Cyn looking laughingly at the stranger, who also laughed.

### CODE REVIEW

**Comment by acabal** [comment]
OK. On seeing these again I actually think we should leave them as-is. I think the sentences could stand with semicolons if the interjection is removed. The only exceptions are `“Yes;” Nattie answered, briefly.` which we can keep, and `“I think not;” Cyn answered. “You won’t` because `You` is capitalized. Either `You` should be lowercased or the semicolon should become a period.

**Comment by tuskpot** [comment]
Got it. Thanks for the explanation. I'll make those adjustments and re-commit.

**Comment by acabal** [comment]
Can you also change the semicolon to a period in the 2nd item? Thanks!

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
